import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  sesotho: {
    nav_home: 'Lehae',
    nav_hymns: 'Lifela',
    nav_prayers: 'Merapelo',
    nav_mass: "Tsamaiso ea 'Misa",
    nav_bible: 'Bibele',
    nav_library: 'Laeborari',
    nav_about: 'Ka Rona',
    tagline: 'Difela Tsa Bakatolike',
    footer_verse: '"O binele Morena sefela se secha" — Pesalema 98:1',
    footer_source_hymns: 'Lifela li nkiloe ho',
    footer_source_church: 'Litaba ho tsoa',
    holy_church: 'Kereke e Halalelang',
    home_title: 'Sefela se Secha',
    home_subtitle: 'Ua amoheloa lenaneong la inthanete la difela le merapelo e tloaelehileng ea Kereke e Katolike.',
    home_btn_hymns: 'Bula Lifela',
    home_btn_mass: 'Tsamaiso ea Misa',
    home_btn_prayers: 'Bula Merapelo',
    home_mission_title: "Ho Boloka Setso sa Tumelo",
    home_mission_text: "Re boloka le ho abelana lifela tsa Kereke ea Katolike. Lipina tsena ke karolo ea boholo ea tumelo ea rona le setso sa rona. Lebitso la rona, 'The Good Shepherd', le re hopotsa hore Jesu ke Molisa ea Molemo ea re tataisang, 'me re mo rorisa ka lipina.",
    home_mission_btn: "Bala Haholoanyane",
    home_news_title: "Litaba tsa Vatican",
    home_news_subtitle: "Mangolo, melaetsa, le liketsahalo tse ncha ho tsoa ho Mopapa le Kereke e Halalelang.",
    home_featured_label: "Sefela sa Letsatsi",
    home_featured_btn: "Bala sefela kaofela →",
    about_title: "Ka",
    about_p1: "The Good Shepherd ke sebaka sa marang-rang se entsoe ho boloka le ho abelana lifela tsa Kereke ea Katolike. Lebitso lena le bolela 'Molisa ea Molemo' — ho re hopotsa hore Molisa oa rona o re bitsa hore re mo rorise.",
    about_p2: "Sebaka sena se na le lifela tse nkiloeng ho Lifela Tsa BaKriste le mehloli e meng, e leng mohloli o moholo oa lifela tsa Bakatolike. Re leboha ba entseng mosebetsi o moholo oa ho boloka lipina tsena.",
    about_p3: "Sepheo sa rona ke hore batho ba fumane lifela tsena habonolo — leha ba le kerekeng, lapeng, kapa leeto-tseleng. Lipina tsena ke karolo ea boholo ea tumelo ea rona le setso sa rona.",
    nav_today: "Kajeno",
    today_liturgy: "Tsamaiso ea Kajeno",
    today_checklist: "Lenane la Semoea",
    today_hymn: "Sefela sa Kajeno",
    today_saint: "Mohalaleli oa Hora",
    today_fact: "Na U ne U Tseba?",
    today_quick_prayers: "Merapelo e Khutšoanyane",
    today_readings: "Lipalo tsa Misa",
    commandments_label: "Litaelo tse Kholo",
    commandments_title: "\"Rata Morena Molimo oa hao...\"",
    commandments_question: "\"Moruti, taelo e kholo molaong ke efe?\"",
    commandments_answer: "Jesu a mo araba a re: \"'<strong style='color: var(--color-burgundy);'>U rate Morena Molimo oa hao ka pelo ea hao eohle, le ka moea oa hao oohle, le ka kelello ea hao eohle.</strong>' Ena ke taelo ea pele, e kholo. 'Me ea bobeli e tšoanang le eona ke ena: '<strong style='color: var(--color-burgundy);'>U rate oa heno joalo ka ha u ithata.</strong>' Molao oohle le Baprofeta ba itšetlehile litaelong tsena tse peli.\"",
    commandments_source: "— Mattheo 22:36-40",
    home_readings_desc: "Kereke e K'hatholike e fana ka liphalo tsa letsatsi le letsatsi bakeng sa 'Misa. Bala litemana tsa kajeno ka botlalo ka tlase.",
    home_readings_btn: "Bala Lipalo Tsa Kajeno →",
    bible_old_testament: "Testamente ea Khale",
    bible_new_testament: "Testamente e Ncha",
    bible_chapter: "Khaolo",
    bible_loading: "E ntse e kenya lintlha...",
    bible_error: "E hlotsoe ho kenya libuka. Ka kopo, hlahloba marang-rang a hau.",
    bookmarks_title: "Litemana Tsa Ka",
    bookmarks_subtitle: "Litemana tsohle tsa hau tseo u li bolokileng Bibeleng.",
    bookmarks_loading: "E ntse e kenya litemana tsa hau...",
    bookmarks_connecting: "E ntse e hokela ak'haonteng ea hau...",
    bookmarks_empty: "Ha u e-s'o boloke litemana leha e le life.",
    bookmarks_start_reading: "Qala ho Bala",
    bookmarks_remove: "Tlosa Temana e Bolokiloeng",
    bookmarks_read_chapter: "Bala Khaolo",
    prayers_common: "Merapelo e Tloaelehileng",
    prayers_private: "Merapelo ea Ka",
    prayers_write_new: "Ngola Thapelo e Ncha",
    prayers_loading: "E ntse e kenya merapelo ea hau...",
    prayers_empty_title: "Bukana ea hau ea merapelo ha e na letho.",
    prayers_empty_desc: "Ngola merapelo ea hau 'me u e boloke e sireletsehile.",
    prayer_editor_title_new: "Ngola Thapelo e Ncha",
    prayer_editor_title_edit: "Fetola Thapelo",
    prayer_editor_label_title: "Sehlooho",
    prayer_editor_placeholder_title: "mohlala. Nyehelo ea Hoseng",
    prayer_editor_label_content: "Thapelo ea Hau",
    prayer_editor_placeholder_content: "Bua le Molimo...",
    prayer_editor_save: "Boloka Thapelo",
    prayer_editor_saving: "Ea boloka...",
    auth_save_data: "Boloka Lintlha tsa Hau",
    auth_welcome_back: "Kena Hape",
    auth_create_desc: "Theha ak'haonte e sa lefelloeng ho boloka bukana le litemana tsa hau ho lisebelisoa tsohle tsa hau.",
    auth_google: "Tsoela pele ka Google",
    auth_email_divider: "Kapa u tsoele pele ka imeile",
    auth_email_label: "Aterese ea imeile",
    auth_password_label: "Lentsoe la sephiri",
    auth_btn_create: "Theha Ak'haonte",
    auth_btn_signin: "Kena",
    auth_switch_to_signin: "U se u na le ak'haonte? Kena mona",
    auth_switch_to_create: "U hloka ak'haonte? Theha e 'ngoe",
    nav_signin: "Kena / Theha Ak'haonte",
    nav_logout: "Tsoa",
    search_placeholder: 'Batla lifela, mantsoe kapa libuka...'
  },
  zulu: {
    nav_home: 'Ikhaya',
    nav_hymns: 'Amaculo',
    nav_prayers: 'Imithandazo',
    nav_mass: 'Inqubo yeMisa',
    nav_bible: 'IBhayibheli',
    nav_library: 'Umtapo',
    nav_about: 'Mayelana Nathi',
    tagline: 'Amaculo amaKhatholika',
    footer_verse: '"Mhubeleni iNkosi ihubo elisha" — AmaHubo 98:1',
    footer_source_hymns: 'Amaculo athathwe ku',
    footer_source_church: 'Ulwazi luvela ku',
    holy_church: 'ISonto eNgcwele',
    home_title: 'Ihubo Elisha',
    home_subtitle: 'Siyakwamukela kule ngosi yama-inthanethi yamaculo nemithandazo ejwayelekile yeSonto lamaKhatholika.',
    home_btn_hymns: 'Vula Amaculo',
    home_btn_mass: 'Inqubo yeMisa',
    home_btn_prayers: 'Vula Imithandazo',
    home_mission_title: "Ukugcina Amasiko Okukholwa",
    home_mission_text: "Sigcina futhi sabelana ngamaculo eSonto lamaKhatholika. Lezi zingoma ziyingxenye enkulu yokholo lwethu namasiko ethu. Igama lethu elithi 'The Good Shepherd' lisikhumbuza ukuthi uJesu unguMalusi Omuhle osiholayo, futhi simdumuza ngengoma.",
    home_mission_btn: "Funda Kabanzi",
    home_news_title: "Izindaba ze-Vatican",
    home_news_subtitle: "Izincwadi, imiyalezo, nezehlakalo zakamuva ezivela kuPapa neSonto eNgcwele.",
    home_featured_label: "Iculo Losuku",
    home_featured_btn: "Funda iculo lonke →",
    about_title: "Mayelana Ne",
    about_p1: "I-The Good Shepherd iyinkundla ye-inthanethi edalelwe ukugcina nokwabelana ngamaculo eSonto lamaKhatholika. Leli gama lisho 'UMalusi Omuhle' — ukusikhumbuza ukuthi uMalusi wethu usibiza ukuba simdumuze.",
    about_p2: "Leli sayithi liqukethe iqoqo lamaculo obuKhatholika athathwe ezincwadini zamaculo ezethembekile. Sibonga labo abenze umsebenzi omkhulu wokulondoloza lezi zingoma.",
    about_p3: "Umgomo wethu ukwenza ukuthi lawa maculo afinyeleleke kalula ebantwini — kungakhathaliseki ukuthi basesontweni, ekhaya, noma basendleleni. Lezi zingoma ziyingxenye enkulu yokholo lwethu namasiko ethu.",
    nav_today: "Namuhla",
    today_liturgy: "Liturgy Yanamuhla",
    today_checklist: "Uhlu Lwezomoya",
    today_hymn: "Iculo Lanamuhla",
    today_saint: "Usanta Wehora",
    today_fact: "Ubusazi?",
    today_quick_prayers: "Imithandazo Emifushane",
    today_readings: "Ukufundwa KweMisa",
    commandments_label: "Imithetho Emikhulu",
    commandments_title: "\"Thanda iNkosi uNkulunkulu wakho...\"",
    commandments_question: "\"Mfundisi, yimuphi umyalo omkhulu eMthethweni?\"",
    commandments_answer: "UJesu wamphendula wathi: \"'<strong style='color: var(--color-burgundy);'>Woyithanda iNkosi uNkulunkulu wakho ngayo yonke inhliziyo yakho, nangawo wonke umphefumulo wakho, nangayo yonke ingqondo yakho.</strong>' Nanku umyalo wokuqala nomkhulu. Owesibili ofana nawo ngowokuthi: '<strong style='color: var(--color-burgundy);'>Wothanda umakhelwane wakho njengalokhu uzithanda wena.</strong>' Kule mithetho yomibili kuncike kuwo wonke uMthetho nabaProfethi.\"",
    commandments_source: "— Mathewu 22:36-40",
    home_readings_desc: "ISonto lamaKhatholika lihlinzeka ngokufundwa kwemiBhalo yansuku zonke yeMisa. Funda imibhalo yeLectionary esemthethweni yanamuhla ngokugcwele ngezansi.",
    home_readings_btn: "Funda Ukufundwa Kwanamuhla →",
    bible_old_testament: "ITestamente Elidala",
    bible_new_testament: "ITestamente Elisha",
    bible_chapter: "Isahluko",
    bible_loading: "Iyalayisha imininingwane yencwane...",
    bible_error: "Ihlulekile ukulayisha izincwadi. Sicela uhlole i-inthanethi yakho.",
    bookmarks_title: "Amabhukumaka Ami",
    bookmarks_subtitle: "Onke amavesi akho owagcinile eBhayibhelini.",
    bookmarks_loading: "Iyalayisha amabhukumaka akho...",
    bookmarks_connecting: "Ixhuma ku-akhawunti yakho...",
    bookmarks_empty: "Awukagcini amavesi okwamanje.",
    bookmarks_start_reading: "Qala Ukufunda",
    bookmarks_remove: "Susa Ibhukumaka",
    bookmarks_read_chapter: "Funda Isahluko",
    prayers_common: "Imithandazo Ejwayelekile",
    prayers_private: "Imithandazo Yami",
    prayers_write_new: "Bhala Umthandazo Omusha",
    prayers_loading: "Iyalayisha imithandazo yakho...",
    prayers_empty_title: "Ijenali yakho yemithandazo ayinalutho.",
    prayers_empty_desc: "Bhala imithandazo yakho uqobo uyigcine ngokuphepha.",
    prayer_editor_title_new: "Bhala Umthandazo Omusha",
    prayer_editor_title_edit: "Hlela Umthandazo",
    prayer_editor_label_title: "Isihloko",
    prayer_editor_placeholder_title: "isb. Umnikelo Wasekuseni",
    prayer_editor_label_content: "Umthandazo Wakho",
    prayer_editor_placeholder_content: "Khuluma noNkulunkulu...",
    prayer_editor_save: "Gcina Umthandazo",
    prayer_editor_saving: "Iyagcina...",
    auth_save_data: "Gcina Imininingwane Yakho",
    auth_welcome_back: "Siyakwamukela Futhi",
    auth_create_desc: "Dala i-akhawunti yamahhala ukuze uvumelanise ijenali namabhukumaka akho kuwo wonke amadivayisi akho.",
    auth_google: "Qhubeka nge-Google",
    auth_email_divider: "Noma qhubeka nge-imeyili",
    auth_email_label: "Ikheli le-imeyili",
    auth_password_label: "Iphasiwedi",
    auth_btn_create: "Dala I-akhawunti",
    auth_btn_signin: "Ngena",
    auth_switch_to_signin: "Usuvele unayo i-akhawunti? Ngena",
    auth_switch_to_create: "Udinga i-akhawunti? Dala enye",
    nav_signin: "Ngena / Dala",
    nav_logout: "Phuma",
    search_placeholder: 'Sesha amaculo, amagama, noma amabhukumaka...'
  },
  xhosa: {
    nav_home: 'Ikhaya',
    nav_hymns: 'Amaculo',
    nav_prayers: 'Imithandazo',
    nav_mass: 'UMthetho weMisa',
    nav_bible: 'IBhayibhile',
    nav_library: 'Ithala',
    nav_about: 'Ngathi',
    tagline: 'Amaculo amaKatolika',
    footer_verse: '"Mvumeleni uNdikhoyo ingoma entsha" — INdumiso 98:1',
    footer_source_hymns: 'Amaculo athatyathwe ku',
    footer_source_church: 'Ulwazi luvela ku',
    holy_church: 'ICawe eNgcwele',
    home_title: 'Ingoma Entsha',
    home_subtitle: 'Wamkelekile kule webhusayithi yamaculo nemithandazo yeCawe yamaKatolika.',
    home_btn_hymns: 'Vula Amaculo',
    home_btn_mass: 'UMthetho weMisa',
    home_btn_prayers: 'Vula Imithandazo',
    home_mission_title: "Ukugcina Isiko Lokholo",
    home_mission_text: "Sigcina kwaye sabelane ngamaculo eCawe yamaKatolika. Ezi ngoma ziyinxalenye enkulu yokholo lwethu nenkcubeko yethu. Igama lethu elithi 'The Good Shepherd' lisikhumbuza ukuba uYesu unguMalusi Olungileyo osikhokelayo, kwaye simdumisa ngengoma.",
    home_mission_btn: "Funda Ngakumbi",
    home_news_title: "Iindaba ze-Vatican",
    home_news_subtitle: "Iincwadi, imiyalezo, neziganeko zamva nje ezivela kuPopu neCawe eNgcwele.",
    home_featured_label: "Ingoma Yosuku",
    home_featured_btn: "Funda ingoma yonke →",
    about_title: "Nge",
    about_p1: "I-The Good Shepherd liqonga le-intanethi elenzelwe ukugcina nokwabelana ngamaculo eCawe yamaKatolika. Eli gama lithetha 'UMalusi Olungileyo' — ukusikhumbuza ukuba uMalusi wethu usibiza ukuba simdumuze.",
    about_p2: "Le sayithi inengqokelela yamaculo obuKatolika athatyathwe kwiincwadi zamaculo ezithembekileyo. Sibulela abo benze umsebenzi omkhulu wokulondoloza ezi ngoma.",
    about_p3: "Injongo yethu kukwenza ukuba la maculo afikeleleke lula ebantwini — nokuba kusecaweni, ekhaya, okanye endleleni. Ezi ngoma ziyinxalenye enkulu yokholo lwethu nenkcubeko yethu.",
    nav_today: "Namhlanje",
    today_liturgy: "Liturgy Yanamhlanje",
    today_checklist: "Uluhlu Lwezomoya",
    today_hymn: "Ingoma Yanamhlanje",
    today_saint: "UmNgcwele Weyure",
    today_fact: "Ubusazi?",
    today_quick_prayers: "Imithandazo Emifutshane",
    today_readings: "Ufundo LweMisa",
    commandments_label: "Imithetho Ebalaseleyo",
    commandments_title: "\"Thanda uNdikhoyo uThixo wakho...\"",
    commandments_question: "\"Mfundisi, nguwuphi na umthetho omkhulu emthethweni?\"",
    commandments_answer: "UYesu wamphendula wathi: \"'<strong style='color: var(--color-burgundy);'>Uze umthande uNdikhoyo uThixo wakho ngentliziyo yakho iphela, nangomphefumlo wakho uphela, nangengqondo yakho iphela.</strong>' Lo ngumthetho wokuqala nomkhulu. Owesibini ofana nawo ngulo: '<strong style='color: var(--color-burgundy);'>Uze umthande ummelwane wakho ngoko uzithanda ngako.</strong>' Kule mithetho mibini kuxhomekeke umthetho wonke nabaProfeti.\"",
    commandments_source: "— UMateyu 22:36-40",
    home_readings_desc: "ICawe yamaKatolika inika ufundo lweZibhalo lwemihla ngemihla lweMisa. Funda imibhalo esemthethweni yanamhlanje ngokupheleleyo ngezantsi.",
    home_readings_btn: "Funda Ufundo Lwanamhlanje →",
    bible_old_testament: "ITestamente Endala",
    bible_new_testament: "ITestamente Entsha",
    bible_chapter: "Isahluko",
    bible_loading: "Iyalayisha iinkcukacha zencwadi...",
    bible_error: "Ayiphumelelanga ukulayisha iincwadi. Nceda ujonge i-intanethi yakho.",
    bookmarks_title: "IiBhukumaka Zam",
    bookmarks_subtitle: "Zonke iivesi zakho ezigciniweyo eBhayibhileni.",
    bookmarks_loading: "Iyalayisha iibhukumaka zakho...",
    bookmarks_connecting: "Iqhagamshela kwi-akhawunti yakho...",
    bookmarks_empty: "Awukagcini nanye ivesi okwangoku.",
    bookmarks_start_reading: "Qala Ukufunda",
    bookmarks_remove: "Susa iBhukumaka",
    bookmarks_read_chapter: "Funda iSahluko",
    prayers_common: "Imithandazo Eqhelekileyo",
    prayers_private: "Imithandazo Yam",
    prayers_write_new: "Bhala uMthandazo oMtsha",
    prayers_loading: "Iyalayisha imithandazo yakho...",
    prayers_empty_title: "Incwadi yakho yemithandazo ayinanto.",
    prayers_empty_desc: "Bhala imithandazo yakho uyigcine ngokukhuselekileyo.",
    prayer_editor_title_new: "Bhala uMthandazo oMtsha",
    prayer_editor_title_edit: "Hlela uMthandazo",
    prayer_editor_label_title: "Isihloko",
    prayer_editor_placeholder_title: "umz. Umnikelo Wakusasa",
    prayer_editor_label_content: "Umthandazo Wakho",
    prayer_editor_placeholder_content: "Thetha noThixo...",
    prayer_editor_save: "Gcina uMthandazo",
    prayer_editor_saving: "Iyagcina...",
    auth_save_data: "Gcina Iinkcukacha Zakho",
    auth_welcome_back: "Wamkelekile Kwakhona",
    auth_create_desc: "Dala i-akhawunti yasimahla ukuze ulungelelanise incwadi yakho kunye neebhukumaka zakho kuzo zonke izixhobo zakho.",
    auth_google: "Qhubeka nge-Google",
    auth_email_divider: "Okanye qhubeka nge-imeyile",
    auth_email_label: "Idilesi ye-imeyile",
    auth_password_label: "Igama lokugqitha",
    auth_btn_create: "Dala iAkhawunti",
    auth_btn_signin: "Ngena",
    auth_switch_to_signin: "Usenayo i-akhawunti? Ngena apha",
    auth_switch_to_create: "Ufuna i-akhawunti? Dala enye",
    nav_signin: "Ngena / Dala",
    nav_logout: "Phuma",
    search_placeholder: 'Khangela amaculo, amagama, okanye iibhukumaka...'
  },
  setswana: {
    nav_home: 'Gae',
    nav_hymns: 'Difela',
    nav_prayers: 'Merapelo',
    nav_mass: 'Tsamaiso ya Misa',
    nav_bible: 'Baebele',
    nav_library: 'Laeborari',
    nav_about: 'Ka Rona',
    tagline: 'Difela Tsa Bakatolike',
    footer_verse: '"Mopeleleng Morena sefela se sesha" — Pesalema 98:1',
    footer_source_hymns: 'Difela di tserwe go',
    footer_source_church: 'Tshedimosetso go tswa',
    holy_church: 'Kereke e e Boitshepo',
    home_title: 'Sefela se Sesha',
    home_subtitle: 'O amogetswe mo webosaeteng ya difela le merapelo ya Kereke e e Katoliki.',
    home_btn_hymns: 'Bula Difela',
    home_btn_mass: 'Tsamaiso ya Misa',
    home_btn_prayers: 'Bula Merapelo',
    home_mission_title: "Go Somarela Ngwao ya Tumelo",
    home_mission_text: "Re somarela le go abelana difela tsa Kereke e e Katoliki. Dipina tse ke karolo e tona ya tumelo ya rona le ngwao ya rona. Leina la rona, 'The Good Shepherd', le re gopotsa gore Jesu ke Modisa yo o Molemo yo o re kaelang, mme re mo rorisa ka pina.",
    home_mission_btn: "Bala Go Fetlha Fao",
    home_news_title: "Dikgang tsa Vatican",
    home_news_subtitle: "Makwalo, melaetsa, le ditiragalo tsa bosheng go tswa go Mopapa le Kereke e e Boitshepo.",
    home_featured_label: "Sefela sa Letsatsi",
    home_featured_btn: "Bala sefela sotlhe →",
    about_title: "Ka",
    about_p1: "The Good Shepherd ke lefelo la inthanete le le diretsweng go somarela le go abelana difela tsa Kereke e e Katoliki. Leina le raya 'Modisa yo o Molemo' — go re gopotsa gore Modisa wa rona o re bitsa gore re mo rorise.",
    about_p2: "Setsha se se na le kokoano ya difela tsa Bokatoliki tse di tserweng mo dibukeng tsa difela tse di ikanngwang. Re leboga ba ba dirileng tiro e tona ya go somarela dipina tse.",
    about_p3: "Maikemisetso a rona ke go dira gore difela tse di bonwe motlhofo ke batho — le fa ba le mo kerekeng, kwa gae, kgotsa ba le mo tseleng. Dipina tse ke karolo e tona ya tumelo ya rona le ngwao ya rona.",
    nav_today: "Gompieno",
    today_liturgy: "Liturgy ya Gompieno",
    today_checklist: "Lenaneo la Semoya",
    today_hymn: "Sefela sa Gompieno",
    today_saint: "Moitshepi wa Ura",
    today_fact: "A o ne o itse?",
    today_quick_prayers: "Merapelo e Mekhutshwane",
    today_readings: "Dipalo tsa Misa",
    commandments_label: "Ditaelo Tse Dikgolo",
    commandments_title: "\"Rata Morena Modimo wa gago...\"",
    commandments_question: "\"Moruti, taelo e kgolo mo Molaong ke efe?\"",
    commandments_answer: "Jesu a mo araba a re: \"'<strong style='color: var(--color-burgundy);'>O rate Morena Modimo wa gago ka pelo ya gago yotlhe, le ka mowa wa gago otlhe, le ka tlhaloganyo ya gago yotlhe.</strong>' E ke taelo ya ntlha, e kgolo. Mme ya bobedi e e tshwanang le yone ke e: '<strong style='color: var(--color-burgundy);'>O rate moagelani wa gago jaaka o ithata.</strong>' Molao otlhe le Baporofeti di ikaegile ka ditaelo tse pedi tse.\"",
    commandments_source: "— Mathaio 22:36-40",
    home_readings_desc: "Kereke e e Katoliki e fana ka dipalo tsa lekwalo la letsatsi le letsatsi tsa Misa. Bala ditemana tsa semmuso tsa gompieno ka botlalo fa tlase.",
    home_readings_btn: "Bala Dipalo Tsa Gompieno →",
    bible_old_testament: "Kgola e Kgologolo",
    bible_new_testament: "Kgola e Ntšha",
    bible_chapter: "Kgaolo",
    bible_loading: "E laisa dintlha tsa buka...",
    bible_error: "E paletswe go laisa dibuka. Tsweetswee tlhatlhoba inthanete ya gago.",
    bookmarks_title: "Matshwao a me a Buka",
    bookmarks_subtitle: "Ditemana tsa gago tsotlhe tse di bolokilweng mo Baebeleng.",
    bookmarks_loading: "E laisa matshwao a gago a buka...",
    bookmarks_connecting: "E golagana le akhaonto ya gago...",
    bookmarks_empty: "Ga o ise o boloke ditemana dipe.",
    bookmarks_start_reading: "Simolola Go Bala",
    bookmarks_remove: "Tlosa Letshwao la Buka",
    bookmarks_read_chapter: "Bala Kgaolo",
    prayers_common: "Merapelo E E Tlwaelegileng",
    prayers_private: "Merapelo Ya Me",
    prayers_write_new: "Kwala Thapelo E Ntšha",
    prayers_loading: "E laisa merapelo ya gago...",
    prayers_empty_title: "Buka ya gago ya merapelo ga e na sepe.",
    prayers_empty_desc: "Kwala merapelo ya gago mme o e boloke sentle.",
    prayer_editor_title_new: "Kwala Thapelo E Ntšha",
    prayer_editor_title_edit: "Fetola Thapelo",
    prayer_editor_label_title: "Setlhogo",
    prayer_editor_placeholder_title: "sekai. Tshupelo ya Moso",
    prayer_editor_label_content: "Thapelo ya Gago",
    prayer_editor_placeholder_content: "Bua le Modimo...",
    prayer_editor_save: "Boloka Thapelo",
    prayer_editor_saving: "Ea boloka...",
    auth_save_data: "Boloka Tshedimosetso ya Gago",
    auth_welcome_back: "Re a Go Amogela Gape",
    auth_create_desc: "Dira akhaonto ya mahala go boloka buka ya gago le matshwao a gago a buka mo didirisiweng tsotlhe tsa gago.",
    auth_google: "Tswelela ka Google",
    auth_email_divider: "Kgotsa tswelela ka imeile",
    auth_email_label: "Aterese ya imeile",
    auth_password_label: "Lefoko-phiri",
    auth_btn_create: "Dira Akhaonto",
    auth_btn_signin: "Tsena",
    auth_switch_to_signin: "O setse o na le akhaonto? Tsena fano",
    auth_switch_to_create: "A o tlhoka akhaonto? Dira e nngwe",
    nav_signin: "Tsena / Dira",
    nav_logout: "Tswa",
    search_placeholder: 'Batla difela, mafoko, kgotsa dibukamak...'
  },
  english: {
    nav_home: 'Home',
    nav_hymns: 'Hymns',
    nav_prayers: 'Prayers',
    nav_mass: 'Order of Mass',
    nav_bible: 'Bible',
    nav_library: 'Library',
    nav_about: 'About Us',
    tagline: 'Catholic Hymns',
    footer_verse: '"Sing to the Lord a new song" — Psalm 98:1',
    footer_source_hymns: 'Hymns sourced from',
    footer_source_church: 'Information from',
    holy_church: 'The Holy Church',
    home_title: 'A New Song',
    home_subtitle: 'Welcome to the online directory of hymns and common prayers of the Catholic Church.',
    home_btn_hymns: 'Open Hymns',
    home_btn_mass: 'Order of Mass',
    home_btn_prayers: 'Open Prayers',
    home_mission_title: "Preserving the Tradition of Faith",
    home_mission_text: "We preserve and share the hymns of the Catholic Church. These songs are a profound part of our faith and heritage. Our name, 'The Good Shepherd', reminds us that Jesus guides us, and we praise Him through song.",
    home_mission_btn: "Read More",
    home_news_title: "Vatican News",
    home_news_subtitle: "Letters, messages, and latest events from the Pope and the Holy Church.",
    home_featured_label: "Hymn of the Day",
    home_featured_btn: "Read full hymn →",
    about_title: "About",
    about_p1: "The Good Shepherd is an online platform created to preserve and share the hymns of the Catholic Church. The name reminds us of Jesus, the Good Shepherd, who calls us to praise Him.",
    about_p2: "This site features a collection of Catholic hymns sourced from trusted hymnals. We thank those who have done the great work of preserving these songs.",
    about_p3: "Our goal is to make these hymns easily accessible to the people — whether in church, at home, or on the go. These songs are a large part of our faith and our culture.",
    nav_today: "Today",
    today_liturgy: "Today's Liturgy",
    today_checklist: "Daily Spiritual Checklist",
    today_hymn: "Daily Hymn",
    today_saint: "Saint of the Hour",
    today_fact: "Did You Know?",
    today_quick_prayers: "Quick Prayers",
    today_readings: "Mass Readings",
    commandments_label: "The Greatest Commandments",
    commandments_title: "\"Love the Lord your God...\"",
    commandments_question: "\"Teacher, which is the greatest commandment in the Law?\"",
    commandments_answer: "Jesus replied: \"'<strong style='color: var(--color-burgundy);'>Love the Lord your God with all your heart and with all your soul and with all your mind.</strong>' This is the first and greatest commandment. And the second is like it: '<strong style='color: var(--color-burgundy);'>Love your neighbor as yourself.</strong>' All the Law and the Prophets hang on these two commandments.\"",
    commandments_source: "— Matthew 22:36-40",
    home_readings_desc: "The Catholic Church provides daily scripture readings for Mass. Read today's official Lectionary texts in full below.",
    home_readings_btn: "Read Today's Readings →",
    bible_old_testament: "Old Testament",
    bible_new_testament: "New Testament",
    bible_chapter: "Chapter",
    bible_loading: "Loading book details...",
    bible_error: "Failed to load books. Please check your connection.",
    bookmarks_title: "My Bookmarks",
    bookmarks_subtitle: "All your saved verses across the Bible.",
    bookmarks_loading: "Loading your bookmarks...",
    bookmarks_connecting: "Connecting to your account...",
    bookmarks_empty: "You haven't bookmarked any verses yet.",
    bookmarks_start_reading: "Start Reading",
    bookmarks_remove: "Remove Bookmark",
    bookmarks_read_chapter: "Read Chapter",
    prayers_common: "Common Prayers",
    prayers_private: "My Prayers",
    prayers_write_new: "Write a New Prayer",
    prayers_loading: "Loading your prayers...",
    prayers_empty_title: "Your prayer journal is empty.",
    prayers_empty_desc: "Write your own personal prayers and save them securely.",
    prayer_editor_title_new: "Write a New Prayer",
    prayer_editor_title_edit: "Edit Prayer",
    prayer_editor_label_title: "Title",
    prayer_editor_placeholder_title: "e.g. Morning Offering",
    prayer_editor_label_content: "Your Prayer",
    prayer_editor_placeholder_content: "Speak to God...",
    prayer_editor_save: "Save Prayer",
    prayer_editor_saving: "Saving...",
    auth_save_data: "Save Your Data",
    auth_welcome_back: "Welcome Back",
    auth_create_desc: "Create a free account to sync your journal and bookmarks across all your devices.",
    auth_google: "Continue with Google",
    auth_email_divider: "Or continue with email",
    auth_email_label: "Email address",
    auth_password_label: "Password",
    auth_btn_create: "Create Account",
    auth_btn_signin: "Sign In",
    auth_switch_to_signin: "Already have an account? Sign in",
    auth_switch_to_create: "Need an account? Create one",
    nav_signin: "Sign In / Up",
    nav_logout: "Log Out",
    search_placeholder: 'Search hymns, lyrics, or bookmarks...'
  }
};

export const languageToBibleId = {
  // Using 42 (CPDV) as a fallback for everything for now until licenses propagate
  sesotho: 42,
  zulu: 42,
  xhosa: 42,
  setswana: 42,
  english: 42,
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [uiLang, setUiLang] = useState(() => {
    return localStorage.getItem('globalUiLang') || 'english';
  });

  useEffect(() => {
    localStorage.setItem('globalUiLang', uiLang);
  }, [uiLang]);

  const t = (key) => {
    return translations[uiLang]?.[key] || translations['english'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ uiLang, setUiLang, t, availableLangs: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
